### ISSUE TITLE
Lint workflow is not working

### ISSUE THREAD

**Issue by kauana** [knative/actions#100]
When the `reusable-style.yaml` workflow was [renamed](https://github.com/knative/actions/commit/a07cee3faf135520010959a17be98c8652d58cb5), the [Lint](https://github.com/knative/actions/blob/main/.github/workflows/lint.yaml#L10) workflow was not updated to address this change and it has been failing ever since ([see example](https://github.com/knative/actions/actions/runs/4184205726)).

**Comment by Nageshbansal** [comment]
Hey @kauana, can I work on this issue?

**Comment by kauana** [comment]
Yes you can :)

**Comment by Nageshbansal** [comment]
Hey @kauana , can you please review my PR #101 .
