### ISSUE TITLE
Unit tests aren't running downstream

### ISSUE THREAD

**Issue by dprotaso** [knative/actions#112]
Unsure why but I think this broke unit tests downstream

https://github.com/knative/caching/pull/733

cc @kvmware @upodroid

_Originally posted by @dprotaso in https://github.com/knative/actions/issues/106#issuecomment-1476360809_

**Comment by upodroid** [comment]
I noticed it too

**Comment by kvmware** [comment]
We saw this in test-infra as well. @dsimansk Any ideas why ?

**Comment by dprotaso** [comment]
I think it was quoting - the updated PR seems to have worked

https://github.com/knative/caching/actions/runs/4463807117/jobs/7852179056?pr=733

**Comment by dsimansk** [comment]
> We saw this in test-infra as well. @dsimansk Any ideas why ?

I believe the quoted var was required by GH action linter. It was never used (and tested) in the former go-test action. Anyway Dave's fix is cleaner and more simple. :)
