### ISSUE TITLE
Older release branches are pointing to deleted workflows

### ISSUE THREAD

**Issue by dprotaso** [knative/actions#114]
ie. https://github.com/knative/serving/blob/release-1.9/.github/workflows/knative-go-test.yaml

We should put the workflows back or update the release branches - so that we can cut point releases

/assign @kvmware

**Comment by kvmware** [comment]
Older branches should probably start pinning/versioning against older actions releases as done in #89

**Comment by dprotaso** [comment]
We don't have tooling/automation for that ATM - so I'd rather not break release branches while that's being sorted out

**Comment by kvmware** [comment]
https://github.com/knative/serving/pull/13809

**Comment by dprotaso** [comment]
This is no longer an issue since the older releases have EOL
